### ISSUE TITLE
path module removed in NodeJS v0.5

### ISSUE THREAD

**Issue by mcandre** [jpolo/node-lint#4]
```
$ cat node-lint
...
require.paths.unshift(LIB_PATH);
...
```

node-lint line 12 needs to be rewritten for the new NodeJS.

```
$ node-lint hello.js

node.js:195
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:360:11)
    at Object.<anonymous> (/usr/local/lib/node/.npm/lint/1.1.0-1/package/bin/node-lint:12:8)
    at Module._compile (module.js:420:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:335:31)
    at Function._load (module.js:294:12)
    at Array.<anonymous> (module.js:479:10)
    at EventEmitter._tickCallback (node.js:187:26)
```

**Comment by jpolo** [comment]
I have not planned to support unstable versions because it is too heavy to maintain as the API is changing.
Although this I will try to correct this bug if I find the time to.
Thanks for your report.

**Comment by jpolo** [comment]
Latest version should fix this problem
